round tables guides 5-7
Ada-Developers-Academy/ada-build pull request #232
Opened 2021-01-21 20:43 UTC by beccaelenzil

Proofreading and any feedback on the content of the questions is much appreciated. I also recognize we will have more information after a couple sessions to update the content of the questions to be most useful for the guided review.

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/05-loops.md
> +    for i in range(2,5):
```suggestion
    for i in range(2, 5):
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/05-loops.md
> +    * What values does `i` take on each time through the loop?
```suggestion
    * What value does `i` take on the first time through the loop?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/05-loops.md
> +    * What values does `i` take on each time through the loop?
```suggestion
    * What value does `i` take on each time through the loop?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/05-loops.md
> +1. What question do you have about *Rock, Paper, Scissors - v3*?
```suggestion
1. What questions do you have about *Rock, Paper, Scissors - v3*?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/06-lists.md
> +1. A single list in python can inlcude elements of multiple data types.
```suggestion
1. A single list in Python can include elements of multiple data types.
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/06-lists.md
> +    * What should we consider when combining different data types in a single list?
```suggestion
    * What should we consider when storing different data types in a single list?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/06-lists.md
> +1. What question do you have about *Rock, Paper, Scissors - v4*?
```suggestion
1. What questions do you have about *Rock, Paper, Scissors - v4*?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/05-loops.md
>  ## Rock, Paper, Scissors - v5
The questions refer to "v3" not "v5".

```suggestion
## Rock, Paper, Scissors - v3
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/07-dictionaries.md
> +1. Describe two ways to access the value stored in a particular key?
```suggestion
1. Describe two ways to access the value associated with a particular key?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/07-dictionaries.md
> +1. What happens if you replicate keys in a dictionary?
```suggestion
1. What happens if you duplicate keys in a dictionary?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/07-dictionaries.md
> +1. Can you use numerical indices to access values from a dictionary. Why or why not?
Just to make the questions stand out more:

```suggestion
1. Only immutable types can be used as keys. 
  * What does it mean for an object to be immutable?
1. Can you use numerical indices to access values inside a dictionary? 
  * Why or why not?
```

2021-01-21 21:47 UTC, kaidamasaki commented on roundtable-guides/07-dictionaries.md
> +1. What question do you have about *Account Generator - v2*?
```suggestion
1. What questions do you have about *Account Generator - v2*?
```

2021-01-22 17:04 UTC, spitsfire requested changes

2021-01-22 17:04 UTC, spitsfire commented on roundtable-guides/06-lists.md
> +1. The Ada Build lessons shows two different ways of looping over a list:
```suggestion
1. The Ada Build lessons show two different ways of looping over a list:
```

2021-01-22 17:04 UTC, spitsfire commented on roundtable-guides/06-lists.md
> +1. Let's Look at Problem 2.5
```suggestion
1. Let's look at problem 2.5
```

2021-01-22 17:04 UTC, spitsfire commented on roundtable-guides/06-lists.md
> +1. What question do you have about *Account Generator*?
```suggestion
1. What questions do you have about *Account Generator*?
```

2021-01-22 17:04 UTC, spitsfire commented on roundtable-guides/06-lists.md
> +1. What question do you have about *Rock, Paper, Scissors - v4*?
```suggestion
1. What questions do you have about *Rock, Paper, Scissors - v4*?
```

2021-01-22 17:32 UTC, smarchante1 requested changes

2021-01-22 17:32 UTC, smarchante1 commented on roundtable-guides/05-loops.md
> +1. What is the fundamental untility of using loops?
```suggestion
1. What is the fundamental utility of using loops?
```

2021-01-26 16:55 UTC, spitsfire approved these changes

2021-01-26 16:56 UTC, merged